### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by ivysrono**
I have tested 1.14.0 Dimensity 1100 by 5 times, the average obtained is 140n/s.

BTW, I have tried to format index.html by VSCode.

### CODE REVIEW

**Comment by ivysrono** [comment]
@HackYardo

**Comment by HackYardo** [comment]
Why @ me? The PR has closed. For Chinese translation? Sorry, I'm busy with work and family in the next three months. My own project, VastGo, is being rewritten and I don't even have time to add translations to it. Finally, BadukAI v1.13 has met my expectations.

You know Chinese, don't you? I'll leave it to you, buddy. Just a hint，each line of the index in Chinese and English is aligned, so you can translate by line!

**Comment by ivysrono** [comment]
只是看之前网页是你翻译的，而且我把网页格式化了，所以提醒下。我也不知道最近是否会有空翻译，再说吧~

**Comment by HackYardo** [comment]
@noword @l1t1 Please anyone translate v1.14 to Chinese in your spare time?

**Pull request merged**
