### PR TITLE
fix zh translation: 赢率 => 胜率

### PR DESCRIPTION
**Pull request by ivysrono**
same as #32

### CODE REVIEW

**Comment by aki65** [comment]
To my eyes, v1.10.0 already contains your changes. git shows no diffs between v1.10.0 and #32 except the speed numbers and the version number that I updated.
Did I overlook something ? Or did you perhaps see an old version from the browser cache ?

**Comment by ivysrono** [comment]
1.10.0 still show `赢率`, so I find this bug.
#32 just edit the web page?

**Comment by aki65** [comment]
When I open https://aki65.github.io/index_zh.html and search for 赢率, I don't find anything. In which line did you see it ?

**Comment by ivysrono** [comment]
> When I open https://aki65.github.io/index_zh.html and search for 赢率, I don't find anything. In which line did you see it ?

This page has been fixed in #32 .
However, this PR try to fix the APP UI in Android.
Same bit not equal.

**Pull request merged**
